document:
  name: Standard publiccode.yml
  description: |
    Questo documento contiene la documentazione relativa allo standard publiccode.yml.
  tags:
    - publiccode.yml 
    - standard 
    - interoperabilità
    - riuso
